spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shepard_db}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

shepard:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

security:
  secret: ${JWT_SECRET}  # Get from env vars
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}